/*
 * Created on 29 Mar 2017 ( Time 09:42:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
@DynamicInsert
@DynamicUpdate
public class Inquiry implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String answer;


    private Integer answerUserId;


    private Date createDate;

    @NotNull
    @Size( min = 1, max = 255 )
    private String question;

    @NotNull
    private Integer status;

    @NotNull
    private Integer typeUser;


    private Date updateDate;


    private Integer askUserId;


    private Integer categoryId;

    @Size( max = 255 )
    private String askEmail;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAnswer( String answer ) {
        this.answer = answer;
    }
    public String getAnswer() {
        return this.answer;
    }

    public void setAnswerUserId( Integer answerUserId ) {
        this.answerUserId = answerUserId;
    }
    public Integer getAnswerUserId() {
        return this.answerUserId;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setQuestion( String question ) {
        this.question = question;
    }
    public String getQuestion() {
        return this.question;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    public void setTypeUser( Integer typeUser ) {
        this.typeUser = typeUser;
    }
    public Integer getTypeUser() {
        return this.typeUser;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setAskUserId( Integer askUserId ) {
        this.askUserId = askUserId;
    }
    public Integer getAskUserId() {
        return this.askUserId;
    }

    public void setCategoryId( Integer categoryId ) {
        this.categoryId = categoryId;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setAskEmail( String askEmail ) {
        this.askEmail = askEmail;
    }
    public String getAskEmail() {
        return this.askEmail;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(answer);
        sb.append("|");
        sb.append(answerUserId);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(question);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(typeUser);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(askUserId);
        sb.append("|");
        sb.append(categoryId);
        sb.append("|");
        sb.append(askEmail);
        return sb.toString(); 
    } 


}
