/*
 * Created on 23 thg 11 2016 ( Time 13:38:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.domain.Sort.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import org.trams.hello.bean.Faq;
import org.trams.hello.bean.jpa.FaqEntity;
import org.trams.hello.business.service.FaqService;
import org.trams.hello.business.service.mapping.FaqServiceMapper;
import org.trams.hello.data.repository.jpa.FaqJpaRepository;
/**
 * Implementation of FaqService
 */
@Component
@Transactional
public class FaqServiceImpl implements FaqService {

	@Resource
	private FaqJpaRepository faqJpaRepository;

	private static final Integer PAGE_SIZE   = 15;

	@Resource
	private FaqServiceMapper faqServiceMapper;
	
	@Override
	public Faq findById(Integer id) {
		FaqEntity faqEntity = faqJpaRepository.findOne(id);
		return faqServiceMapper.mapFaqEntityToFaq(faqEntity);
	}

	@Override
	public Page<FaqEntity> findAll(Integer pageNumber) {

		PageRequest request = new PageRequest(pageNumber - 1, PAGE_SIZE,
				new Sort(new Order(Direction.DESC, "id")));
		return faqJpaRepository.findAll(request);
	}

	@Override
	public List<Faq> findAll() {
		Iterable<FaqEntity> entities = faqJpaRepository.findAll();
		List<Faq> beans = new ArrayList<Faq>();
		for(FaqEntity faqEntity : entities) {
			beans.add(faqServiceMapper.mapFaqEntityToFaq(faqEntity));
		}
		return beans;
	}

	/**
	 * Count total entit
	 * @return Long
	 */
	public Long countTotal(){
		Long count = faqJpaRepository.count();
		return count;
	}

	@Override
	public Faq save(Faq faq) {
		return update(faq) ;
	}

	@Override
	public Faq create(Faq faq) {
/*
		FaqEntity faqEntity = faqJpaRepository.findOne(faq.getId());
		if( faqEntity != null ) {
			throw new IllegalStateException("already.exists");
		}

		faqEntity = new FaqEntity();
		faqServiceMapper.mapFaqToFaqEntity(faq, faqEntity);
		FaqEntity faqEntitySaved = faqJpaRepository.save(faqEntity);
		return faqServiceMapper.mapFaqEntityToFaq(faqEntitySaved);
*/
		FaqEntity faqEntity = new FaqEntity();
		faqServiceMapper.mapFaqToFaqEntity(faq, faqEntity);
		FaqEntity faqEntitySaved = faqJpaRepository.save(faqEntity);
		return faqServiceMapper.mapFaqEntityToFaq(faqEntitySaved);
	}

	@Override
	public Faq update(Faq faq) {
		FaqEntity faqEntity = faqJpaRepository.findOne(faq.getId());
		faqServiceMapper.mapFaqToFaqEntity(faq, faqEntity);
		FaqEntity faqEntitySaved = faqJpaRepository.save(faqEntity);
		return faqServiceMapper.mapFaqEntityToFaq(faqEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		faqJpaRepository.delete(id);
	}

	public FaqJpaRepository getFaqJpaRepository() {
		return faqJpaRepository;
	}

	public void setFaqJpaRepository(FaqJpaRepository faqJpaRepository) {
		this.faqJpaRepository = faqJpaRepository;
	}

	public FaqServiceMapper getFaqServiceMapper() {
		return faqServiceMapper;
	}

	public void setFaqServiceMapper(FaqServiceMapper faqServiceMapper) {
		this.faqServiceMapper = faqServiceMapper;
	}

	@Override
	public Page<FaqEntity> listPaging(Integer page, Integer size) {
		try {
			PageRequest pageable = new PageRequest(page-1, size, new Sort(new Order(Direction.DESC, "createDate")));
			return faqJpaRepository.listPaging(pageable);
		} catch (Exception e) {
			System.out.println(e);
			return null;
		}
	}
	
	

	@Override
	public Page<FaqEntity> findByTitle(String title, Integer page, Integer size) {
		try {
			PageRequest pageable = new PageRequest(page-1, size, new Sort(new Order(Direction.DESC, "createDate")));
			return faqJpaRepository.findByTitle(title, pageable);
		} catch (Exception e) {
			System.out.println(e);
			return null;
		}
	}
	
	@Override
	public List<FaqEntity> findByTitleOrContent(String keyword) {
		try {
			return faqJpaRepository.findByTitleOrContent("%"+keyword+"%");
		} catch (Exception e) {
			System.out.println(e);
			return null;
		}
	}

	
	@Override
	public List<Faq> listByIsShow() {
		List<FaqEntity> entities = faqJpaRepository.listByIsShow();
		List<Faq> beans = new ArrayList<>();
		for (FaqEntity f : entities) {
			beans.add(faqServiceMapper.mapFaqEntityToFaq(f));
		}
		return beans;
	}
	
	@Override
	public List<Faq> listInCounselorWeb() {
		List<FaqEntity> entities = faqJpaRepository.listInCounselorWeb();
		List<Faq> beans = new ArrayList<>();
		for (FaqEntity f : entities) {
			beans.add(faqServiceMapper.mapFaqEntityToFaq(f));
		}
		return beans;
	}

	@Override
	public List<Faq> listByIsShowAndType(Short type) {
		List<FaqEntity> entities = faqJpaRepository.listByIsShowAndType(type);
		List<Faq> beans = new ArrayList<>();
		for (FaqEntity f : entities) {
			beans.add(faqServiceMapper.mapFaqEntityToFaq(f));
		}
		return beans;
	}

}
