/*
 * Created on 23 thg 11 2016 ( Time 13:38:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.impl;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.EntityManager;
import javax.persistence.Query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.data.domain.Sort.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import org.trams.hello.bean.Message;
import org.trams.hello.bean.PageCustom;
import org.trams.hello.bean.UserReceiveMessage;
import org.trams.hello.bean.jpa.MessageEntity;
import org.trams.hello.bean.jpa.UserEntity;
import org.trams.hello.bean.web.counselor.InboxMessages;
import org.trams.hello.bean.web.counselor.SendMessages;
import org.trams.hello.business.service.MessageService;
import org.trams.hello.business.service.UserReceiveMessageService;
import org.trams.hello.business.service.UserService;
import org.trams.hello.business.service.mapping.MessageServiceMapper;
import org.trams.hello.data.repository.jpa.MessageJpaRepository;
import org.trams.hello.data.repository.jpa.UserReceiveMessageJpaRepository;
/**
 * Implementation of MessageService
 */
@Component
@Transactional
public class MessageServiceImpl implements MessageService {

	@Resource
	private MessageJpaRepository messageJpaRepository;
	@Resource
	private UserService userService;
	@Resource
	private UserReceiveMessageJpaRepository userReceiveMessageJpaRepository;

	private static final Integer PAGE_SIZE   = 15;

	@Resource
	private MessageServiceMapper messageServiceMapper;
	
	@Autowired
	private EntityManager em;
	
	@Resource
	private UserReceiveMessageService userReceiveMessageService;
	
	@Override
	public Message findById(Integer id) {
		MessageEntity messageEntity = messageJpaRepository.findOne(id);
		return messageServiceMapper.mapMessageEntityToMessage(messageEntity);
	}

	@Override
	public Page<MessageEntity> findAll(Integer pageNumber) {

		PageRequest request = new PageRequest(pageNumber - 1, PAGE_SIZE,
				new Sort(new Order(Direction.DESC, "id")));
		return messageJpaRepository.findAll(request);
	}

	@Override
	public List<Message> findAll() {
		Iterable<MessageEntity> entities = messageJpaRepository.findAll();
		List<Message> beans = new ArrayList<Message>();
		for(MessageEntity messageEntity : entities) {
			beans.add(messageServiceMapper.mapMessageEntityToMessage(messageEntity));
		}
		return beans;
	}

	/**
	 * Count total entit
	 * @return Long
	 */
	public Long countTotal(){
		Long count = messageJpaRepository.count();
		return count;
	}

	@Override
	public Message save(Message message) {
		return update(message) ;
	}

	@Override
	public Message create(Message message) {
		MessageEntity messageEntity = new MessageEntity();
		messageServiceMapper.mapMessageToMessageEntity(message, messageEntity);
		MessageEntity messageEntitySaved = messageJpaRepository.save(messageEntity);
		
		return messageServiceMapper.mapMessageEntityToMessage(messageEntitySaved);
	}

	@Override
	public Message update(Message message) {
		MessageEntity messageEntity = messageJpaRepository.findOne(message.getId());
		messageServiceMapper.mapMessageToMessageEntity(message, messageEntity);
		MessageEntity messageEntitySaved = messageJpaRepository.save(messageEntity);
		return messageServiceMapper.mapMessageEntityToMessage(messageEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		messageJpaRepository.delete(id);
	}

	public MessageJpaRepository getMessageJpaRepository() {
		return messageJpaRepository;
	}

	public void setMessageJpaRepository(MessageJpaRepository messageJpaRepository) {
		this.messageJpaRepository = messageJpaRepository;
	}

	public MessageServiceMapper getMessageServiceMapper() {
		return messageServiceMapper;
	}

	public void setMessageServiceMapper(MessageServiceMapper messageServiceMapper) {
		this.messageServiceMapper = messageServiceMapper;
	}

	@Override
	public Page<MessageEntity> listPaging(Integer page, Integer size) {
		try {
			PageRequest pageable = new PageRequest(page-1, size, new Sort(new Order(Direction.DESC, "createDate")));
			return messageJpaRepository.listPaging(pageable);
		} catch (Exception e) {
			System.out.println(e);
			return null;
		}
	}

	@Override
	public Message send(Map<String, Object> params) {

		int toId 		= Integer.parseInt(params.get("toId").toString());
		int fromId 		= Integer.parseInt(params.get("fromId").toString());
		int type 		= Integer.parseInt(params.get("type").toString());
		String content 	= (String) params.get("content");
		Date now 		= Calendar.getInstance().getTime();

		UserEntity sendUserEntity = new UserEntity();
		sendUserEntity.setId(fromId);

		UserEntity receiveUserEntity = new UserEntity();
		receiveUserEntity.setId(toId);

		MessageEntity message = new MessageEntity();

		message.setContent(content);
		message.setSendDate(now);
		message.setRecieveDate(now);
		message.setUpdateDate(now);
		message.setCreateDate(now);
		message.setTypeUser(type);
		message.setUser(sendUserEntity);

		MessageEntity messageEntitySaved = messageJpaRepository.save(message);

		UserReceiveMessage userReceiveMessage = new UserReceiveMessage();
		userReceiveMessage.setCreateDate(now);
		userReceiveMessage.setUpdateDate(now);
		userReceiveMessage.setStatus((short) 0);
		userReceiveMessage.setMessageId(messageEntitySaved.getId());
		userReceiveMessage.setUserId(toId);

		userReceiveMessageService.create(userReceiveMessage);

		return messageServiceMapper.mapMessageEntityToMessage(messageEntitySaved);
	}

	@Override
	public MessageEntity findByMessageId(Integer id) {
		return messageJpaRepository.findByMessageId(id);
	}

	@Override
	public PageCustom<InboxMessages> filterInboxMessagesOfCounselor(String start_search, String end_search, String keyword,
			Integer counselorId, Integer page, Integer size, String orderBy) {
		try {
			List<InboxMessages> list = new ArrayList<>();
			String str_select = "SELECT ur.id AS urd, m.id AS mId, u.id AS uId, u.email, u.fullname, m.content, ur.create_date, m.type_user ";
			String str_count = "SELECT count(*) ";
			String str_from = " FROM user_receive_message ur "
					+ " INNER JOIN message m ON ur.message_id = m.id "
					+ " INNER JOIN user u ON m.send_user_id = u.id ";
			
			String str_where = " WHERE ur.user_id = :counselorId "
					+ " and DATE(ur.create_date) >= :start_search and DATE(ur.create_date) <= :end_search AND m.is_delete = 0 ";
			
			String str_wh_keyword = "";
			if(keyword != null) {
				str_wh_keyword = " and (u.fullname like :key or m.content like :key) ";
			}
			String str_orderby = "";
			if(orderBy.equals("create_date_mess")){
				str_orderby = " ORDER BY ur.create_date DESC " ;
			} else {
				str_orderby = " ORDER BY u.fullname ASC " ;
			}
			
			Query q = em.createNativeQuery(str_select + str_from + str_where + str_wh_keyword + str_orderby + " limit " + (page-1)*size  + ", " + size);
			q.setParameter("counselorId", counselorId);
			q.setParameter("end_search", end_search);
			q.setParameter("start_search", start_search);
			if (keyword != null) {
				q.setParameter("key", "%"+keyword+"%");
			}

			@SuppressWarnings("unchecked")
			List<Object[] > rss = q.getResultList();
			for (Object[] i : rss) {
				InboxMessages iMess = new InboxMessages();
				iMess.setId((Integer) i[0]);
				iMess.setMessageId((Integer) i[1]);
				iMess.setUserId((Integer) i[2]);
				iMess.setUserEmail((String) i[3]);
				iMess.setUserName((String) i[4]);
				iMess.setContent((String) i[5]);
				iMess.setReceivedDate((Date) i[6]);
				iMess.setTypeUser((Integer) i[7]); 
				list.add(iMess);
			}
			
			Query c = em.createNativeQuery(str_count + str_from + str_where + str_wh_keyword + str_orderby);
			c.setParameter("counselorId", counselorId);
			c.setParameter("end_search", end_search);
			c.setParameter("start_search", start_search);
			if (keyword != null) {
				c.setParameter("key", "%"+keyword+"%");
			}
			
			Integer totalCount = Integer.valueOf(c.getSingleResult().toString());
			if(totalCount == null) {
				totalCount = 0;
			}
			PageCustom<InboxMessages> pageCustom = new PageCustom<>(list, totalCount, page, size);
			
			return pageCustom;
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

	@Override
	public PageCustom<SendMessages> filterSendMessagesOfCounselor(String start_search, String end_search,
			String keyword, Integer counselorId, Integer page, Integer size, String orderBy) {
		try {
			List<SendMessages> list = new ArrayList<>();
			String str_select = "SELECT ur.id AS urd, m.id AS mId, u.id AS uId, u.email, u.fullname, m.content, m.send_date , m.type_user ";
			String str_count = "SELECT count(*) ";
			String str_from = " FROM user_receive_message ur "
					+ " INNER JOIN user u ON ur.user_id = u.id "
					+ " INNER JOIN message m ON ur.message_id = m.id ";
			
			String str_where = " WHERE m.is_delete = 0 AND m.send_user_id = "+counselorId+" "
					+ " and DATE(m.send_date) >= '"+start_search+"' and DATE(m.send_date) <= '"+end_search+"' ";
			
			String str_wh_keyword = "";
			if(keyword != null) {
				String key = "%"+keyword+"%";
				str_wh_keyword = " and (u.fullname like '"+key+"' or m.content like '"+key+"') ";
			}
			String str_orderby = " ";
			if(orderBy.equals("create_date_mess")){
				str_orderby = " ORDER BY ur.create_date DESC " ;
			} else {
				str_orderby = " ORDER BY u.fullname ASC " ;
			}
			
			Query q = em.createNativeQuery(str_select + str_from + str_where + str_wh_keyword + str_orderby + " limit " + (page-1)*size  + ", " + size);
			@SuppressWarnings("unchecked")
			List<Object[] > rss = q.getResultList();
			
			for (Object[] i : rss) {
				SendMessages sMess = new SendMessages();
				sMess.setId((Integer) i[0]);
				sMess.setMessageId((Integer) i[1]);
				sMess.setUserId((Integer) i[2]);
				sMess.setUserEmail((String) i[3]);
				sMess.setUserName((String) i[4]);
				sMess.setContent((String) i[5]);
				sMess.setSendDate((Date) i[6]);
				sMess.setTypeUser((Integer) i[7]);
				list.add(sMess);
			}
			
			Query c = em.createNativeQuery(str_count + str_from + str_where + str_wh_keyword + str_orderby);
			Integer totalCount = Integer.valueOf(c.getSingleResult().toString());
			if(totalCount == null) {
				totalCount = 0;
			}
			PageCustom<SendMessages> pageCustom = new PageCustom<>(list, totalCount, page, size);
			
			return pageCustom;
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

	@Override
	public void updateIsDeleteByMessageId(Integer id) {
		try {
			messageJpaRepository.updateIsDeleteByMessageId(id);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}


}
